
g++ -m32 -Wall -Wno-deprecated -g -I /usr/include/lua5.1 -L ./ -L /usr/lib -llua5.1 ./module.cpp -o ./module
#g++ -m32 -Wall -g -I /usr/include/lua5.1 -L ./ -L /usr/lib -llua5.1 ./module.cpp -o ./module
